### ISSUE TITLE
Drop tests from default build; enable tests in CI

### ISSUE THREAD

**Issue by ddn0** [KatanaGraph/katana#110]
Tests are really only relevant for developers. Benchmarking code and system debugging code also is really only relevant to developers. We should have some option to exclude these bits for standard user builds while still enabling everything during CI.

Related: https://github.com/IntelligentSoftwareSystems/Galois/issues/223

**Comment by arthurp** [comment]
And in fact we only need it in __some__ CI builds. The conda builds would be much faster with tests not being built; it's something like 80% of the build time. I tried to avoid building them, but `make install` forces all the tests to build even though they are not installed.

Could we just exclude all the tests and benchmark tools from the `all` target and setup a `tests` target that people can either invoke directly and depend on for actual testing targets.
