### ISSUE TITLE
Document use of git submodules better and handle failures more cleanly

### ISSUE THREAD

**Issue by arthurp** [KatanaGraph/katana#115]
The README should probably be updated to specify that we require submodules to be initialized and updated. Also the build file for tools/graph-convert should probably check for the submodule and print a useful message similarly to how it's handled in libgpu:

https://github.com/KatanaGraph/katana/blob/0b604f39d209eb791bbd135425413b5bb39a26d3/libgpu/CMakeLists.txt#L25-L27

Currently not checking out submodules on a normal build just results in a missing include file `csv.hpp` and it's not obvious this is expected to be in a submodule instead of be a package installed on the system before build.

**Comment by yuhc** [comment]
Like it.

**Comment by ddn0** [comment]
A similar line has been added for external/csv-parser.
