### ISSUE TITLE
Invalid version error during installation

### ISSUE THREAD

**Issue by narendrachaudhary51** [KatanaGraph/katana#185]
Following discussion from https://github.com/KatanaGraph/katana/issues/70.
I do the following steps to install katana. I get invalid version errors at the corresponding steps.

1. git clone https://github.com/KatanaGraph/katana.git
2. SRC_DIR=/home/katana
3. conda env create --name katana-dev --file $SRC_DIR/conda_recipe/environment.yml
4. conda activate katana-dev 
5. conda install -c conda-forge numactl-devel-cos6-x86_64
6. BUILD_DIR=/home/katana/build
7. mkdir -p $BUILD_DIR
8. cmake -S $SRC_DIR -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release -DKATANA_LANG_BINDINGS=python -DBUILD_SHARED_LIBS=ON
9. conda build -c conda-forge $SRC_DIR/conda_recipe/
         **ERROR - anaconda3/lib/python3.8/site-packages/conda/models/version.py", line 164, in __init__
    raise InvalidVersionSpec(vstr, "empty version string")
conda.exceptions.InvalidVersionSpec: Invalid version '': empty version string**

10. cd $BUILD_DIR
11. make -j 8
         **ERROR - /home/katana/build/katana_python_build/scripts/katana_version/version.py", line 177, in get_explicit_version
    explicit_version = tag_version or get_config_version(
  File "/home/katana/build/katana_python_build/scripts/katana_version/version.py", line 197, in get_config_version
    with open(Path(__file__).parent.parent.parent / CONFIG_VERSION_PATH, "rt") as version_file:**

12. make clean
13.  rm CMakeCache.txt
14. cd $SRC_DIR
15. cmake -S $SRC_DIR -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release
16. cd $BUILD_DIR
17. make -j 8
       **Done**

**Comment by arthurp** [comment]
Thank you. There are several different issues here. Let me split this up to hopefully clarify it.

You installed things correctly, Great!
<details>

```
$ git clone https://github.com/KatanaGraph/katana.git
$ SRC_DIR=/home/katana
$ conda env create --name katana-dev --file $SRC_DIR/conda_recipe/environment.yml
$ conda activate katana-dev
$ conda install -c conda-forge numactl-devel-cos6-x86_64
```
</details>

You are mixing different builds here. `conda build` is totally self contained. If you want to build conda packages you just call `conda build` and that's it. Also you don't need to build the conda package, though. You can just do a normal build.
```
$ BUILD_DIR=/home/katana/build
$ mkdir -p $BUILD_DIR
$ cmake -S $SRC_DIR -B $BUILD_DIR -DCMAKE_BUILD_TYPE=Release -DKATANA_LANG_BINDINGS=python -DBUILD_SHARED_LIBS=ON
$ conda build -c conda-forge $SRC_DIR/conda_recipe/
ERROR - anaconda3/lib/python3.8/site-packages/conda/models/version.py", line 164, in init
raise InvalidVersionSpec(vstr, "empty version string")
conda.exceptions.InvalidVersionSpec: Invalid version '': empty version string
```
This is an odd error. I wouldn't expect it. I'll look into this.

```
$ cd $BUILD_DIR
$ make -j 8
ERROR - /home/katana/build/katana_python_build/scripts/katana_version/version.py", line 177, in get_explicit_version
explicit_version = tag_version or get_config_version(
File "/home/katana/build/katana_python_build/scripts/katana_version/version.py", line 197, in get_config_version
with open(Path(file).parent.parent.parent / CONFIG_VERSION_PATH, "rt") as version_file:
```
The fact that you also get this error here is strange. I have some kind of idea, though. Hmm. Can you send me the complete error message? You seem to have truncated the error message.

**Comment by narendrachaudhary51** [comment]
This is the full error message

```
Checking for Python package 'packaging'...Found 20.9.
Traceback (most recent call last):
  File "/home/katana/build/katana_python_build/setup.py", line 18, in <module>
    package_setup()
  File "/home/katana/build/katana_python_build/setup.py", line 14, in package_setup
    katana_setup.setup(source_dir="python", package_name="katana", doc_package_name="Katana Python")
  File "/home/katana/build/katana_python_build/python/katana_setup.py", line 378, in setup
    version=get_katana_version(),
  File "/home/katana/build/katana_python_build/python/katana_setup.py", line 416, in get_katana_version
    return str(katana_version.version.get_version())
  File "/home/katana/build/katana_python_build/scripts/katana_version/version.py", line 67, in get_version
    k_explicit_version, variant = get_explicit_version(
  File "/home/katana/build/katana_python_build/scripts/katana_version/version.py", line 177, in get_explicit_version
    explicit_version = tag_version or get_config_version(
  File "/home/katana/build/katana_python_build/scripts/katana_version/version.py", line 197, in get_config_version
    with open(Path(__file__).parent.parent.parent / CONFIG_VERSION_PATH, "rt") as version_file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/katana/build/katana_python_build/config/version.txt'
make[2]: *** [CMakeFiles/katana_python.dir/build.make:71: CMakeFiles/katana_python] Error 1
make[1]: *** [CMakeFiles/Makefile2:1541: CMakeFiles/katana_python.dir/all] Error 2
```

**Comment by arthurp** [comment]
What platform are you on? Distribution. Architecture. Version of cmake.

(Detail: It appears that an environment variable is getting lost between cmake and setuptools call. Or that cmake is failing to set the environment variable.)

**Comment by narendrachaudhary51** [comment]
I am on CentOS 7, x86 architecture. cmake version 3.19.5

**Comment by arthurp** [comment]
Thanks. I will look at this when I have time. It may take a week or two to get this specific issue fixed. Hopefully, I can still help you get things built so you can use it.
