### ISSUE TITLE
katana::Result cannot be used with std::async

### ISSUE THREAD

**Issue by arthurp** [KatanaGraph/katana#227]
The issue is that `std::async` may run the closure passed to it in another thread. However, `katana::Result` and `ErrorInfo` are tied to a specific thread because of the use of thread local storage (to optimize returning those values). The result is that code that uses `async` with `Result` will fail on specific runtimes in unpredictable ways. The error that caused me to discover this is only reproducible on my local machine and not in CI.

An example of code that uses `Result` unsafely is:
https://github.com/KatanaGraph/katana/blob/32d2999c2ead47de03e9d5c233a4a5cbd05b7cf6/libtsuba/src/LocalStorage.cpp#L124-L127
https://github.com/KatanaGraph/katana/blob/32d2999c2ead47de03e9d5c233a4a5cbd05b7cf6/libtsuba/src/LocalStorage.cpp#L143-L147

The solution to this is to create a variant of `katana::Result` that is thread safe. It will use `CopyableErrorInfo` in place of `ErrorInfo`. Explicit conversions will be needed between the two forms. This variant will need to be used any time an error could be passed between threads.

Ideally, we would also make it an error to place a `Result` inside something that will pass between threads, but there really isn't any way to do this in C++. But we could do a few ad-hoc things like specializing `std::future<katana::Result>` to be an error. This may not be standards compliant, but if we guard it with compiler check macros it would still be useful as long as the specialization works on the compilers we run in CI.

**Comment by ddn0** [comment]
Another option would be to wrap `std::async` as `katana::async` and have a specialization that copies thread-local return values correctly.

std::async has implementation-defined behavior https://ddanilov.me/std-async-implementations/ anyway and this would be a decent entrypoint towards enforcing launching a new thread always or future async implementations with a thread pool or integrating `do_all` with `async` (via: std::promise).

**Comment by arthurp** [comment]
> this would be a decent entrypoint towards enforcing launching a new thread always or future async implementations with a thread pool or integrating `do_all` with `async` (via: std::promise).

I think `katana::async` is a great idea. As a parallelism library I definitely think taking ownership of all our threading is a good idea. I had already had the thought that it was weird that we didn't reuse the galois thread pool for our async operations. Though it would be a dependency issue since the thread pool is in `libgalois`, but the async usage I have seen is in `libtsuba`.

One complication is making sure that our `katana::async` correctly integrates with external C++ libraries that expose `std::future` or related type in their APIs somehow.

**Comment by ddn0** [comment]
I think we can still return a `std::future` by just using `std::promise` https://en.cppreference.com/w/cpp/thread/promise .

But yes, one blocker to a full thread pool is resolving the dependency between libgalois -> libtsuba -> libsupport . I don't think there is anything preventing us from moving relevant bits from `libgalois` to `libsupport` while keeping `libgalois` to just to data structures and above.

**Comment by arthurp** [comment]
I think we will still need a `CopyableResult` of some kind though, so people can use it in cases where `katana::async` isn't applicable, like if the code will run in an externally controlled thread pool (Go's for instance). I also worry about making `katana::async` too transparent because it will make it easy to forget that if a `Result` goes between threads it must be specially handled.

It sounds like you are proposing that the thread pool would be moved to `libsupport` along with at least some of the parallelism constructs. This makes some sense to me. We could still keep `do_all` and `for_each` in `libgalois`, but move the lower level thread pool implementation to `libsupport`.

A problem I see with this is that the thread pool is totally synchronous (in `runInternal`). So I don't know if it's possible to use it to implement `async` in any reasonable way. We would have to add a way to "start and return" a task, but the design of the thread pool isn't really appropriate for that, so I kinda think that would break things. So it may not be possible to share the thread pool with async tasks.
