### ISSUE TITLE
Boost 1.73.0 would allow for a more efficient ArrowRandomAccessBuilder

### ISSUE THREAD

**Issue by danielmawhirter** [KatanaGraph/katana#238]
[ArrowRandomAccessBuilder ](https://github.com/KatanaGraph/katana/blob/master/libgalois/include/katana/ArrowRandomAccessBuilder.h) constructs an arrow::Array from `<index, value>` pairs arriving in unknown order, and needs to be thread-safe and nullable, so we keep track of the null bitmask as one-byte-per-element uint8_t values while building in a std::vector, then allocate arrow's Builder memory and copy into it.

In order to use arrow's Builder memory directly (for PODs), we would need thread-safe write access to the one-bit-per-element null bitmask. c++20 has the `atomic_ref` feature which would enable this, and boost >= 1.73.0 has an implementation that would work. as follows:

Instead of arrow's version:
```c++
static inline void SetBit(uint8_t* bits, int64_t i) {
  bits[i / 8] |= kBitmask[i % 8];
}
```
we would use our version:
```c++
static inline void AtomicSetBit(uint8_t* bits, int64_t i) {
  boost::atomic_ref<uint8_t> ref(bits[i / 8]);
  ref.opaque_or(kBitmask[i % 8], boost::memory_order::relaxed);
}
```
both using:
```c++
static constexpr uint8_t kBitmask[] = {1, 2, 4, 8, 16, 32, 64, 128};
```

String would still need separate a implementation, since they have variable size per element and can't be readily pre-allocated.

How feasible is it to bump the Boost version from 1.58.0 to 1.73.0+?

**Comment by arthurp** [comment]
Conda builds have been using at least 1.72 for a long while. And open builds have been using 1.74. This should be trivial to upgrade. Just change the version number in conan (and conda since I think we only have 1.72 as a minimum for boost).
