### ISSUE TITLE
Factor out logging into it's own support library

### ISSUE THREAD

**Issue by tylershunt** [KatanaGraph/katana#32]
It makes sense to be able to control logging via one interface. Galois has fairly standard internal logging system but it can't be called from the libraries that Galois depends on (like the new storage library).

**Comment by ddn0** [comment]
More context: currently galois::substrate is the home for low-level shared functionality

**Comment by ddn0** [comment]
Also there are some poorly named functions like `printOutput` which write to a log file and are in `Tracer.h`:
https://github.com/KatanaGraph/katana/blob/master/libgalois/include/galois/runtime/Tracer.h#L155
