### ISSUE TITLE
Undo `LargeStringArray` hack when we move to arrow 3 (currently required to support parquet)

### ISSUE THREAD

**Issue by tylershunt** [KatanaGraph/katana#62]

**Comment by tylershunt** [comment]
The `LargeStringArray`->`StringArray` tango happening in #61

**Comment by arthurp** [comment]
@tylershunt We are on arrow 4 now. Might be time to revisit this issue soon.

**Comment by tylershunt** [comment]
It's partially addressed. Parquet has no large string representation (AFAICT), so while storing a large string will now work, reading the files we wrote will still result in normal, non-large strings.
