### ISSUE TITLE
GPU applications not support compute capability >7.0

### ISSUE THREAD

**Issue by yuhc** [KatanaGraph/katana#72]
A few GPU applications such as `mst` require changes to support newer PTX versions and (Turing) GPU architectures.

```
ptxas /tmp/tmpxft_00007853_00000000-5_pta.ptx, line 37549;
error   : Instruction 'vote' without '.sync' is not supported on .target sm_70 and higher from PTX ISA version 6.4
```

**Comment by yuhc** [comment]
Running `./lonestar/analytics/gpu/pagerank/pagerank_gpu inputs/stanford/communities/DBLP/com-dblp.wgt32.sym.gr.triangles` on NVIDIA M60 (sm_52), I also got an error on `cudaMalloc`:

```
/home/ubuntu/katana/libgpu/src/csr_graph.cu:55: unknown error (999)
```

**Comment by nicelhc13** [comment]
Have you checked "GALOIS_CUDA_CAPABILITY" on CCMakeCache.txt?
It might be occurred since the proper GPU capability was not set.

**Comment by yuhc** [comment]
> Have you checked "GALOIS_CUDA_CAPABILITY" on CCMakeCache.txt?
> It might be occurred since the proper GPU capability was not set.

Yes, and the build works with sm_52 and sm_61,  but fails with sm_70 and sm_75.

**Comment by vishweshjatala** [comment]
ModernGPU is also updated. Created a pull request #305.
@chenxuhao also a created PR #302 to fix other GPU app.
Now this can be closed after merging.

**Comment by vishweshjatala** [comment]
ModernGPU is also updated. Created a pull request https://github.com/IntelligentSoftwareSystems/Galois/pull/305.
@chenxuhao also a created PR https://github.com/IntelligentSoftwareSystems/Galois/pull/302 to fix other GPU app.
Now this can be closed after merging.

**Comment by yuhc** [comment]
Thank you for this @vishweshjatala !

I guess the sync of this repo will be a separate process handled by the Katana guys. I leave a comment here as a reminder.
